### PR TITLE
Updating course for Rust 2018

### PR DESCRIPTION
**Pull request by spacekookie**
So far this PR only addresses the crate and macro changes around `extern crate`.

Futures will require some more research.

So far not covered at all are modules in detail, is that right? Do we want to mention the whole `foo/mod.rs` vs `foo.rs` thing?

### CODE REVIEW

**Comment by skade** [comment]
I'm not sure I would completely remove the 2015 versions until the edition is actually released (and then some). Maybe adding an additional slide for 2018 or even some way of switching between the two examples?

**Comment by spacekookie** [comment]
Ping @skade: Please let me know if there are any things you want changed.

**Comment by spacekookie** [comment]
Things that the "Future of Futures" chapter is still missing

- More `futures-rs` examples
- Any tokio explanation and examples
- Maybe `Fahrenheit`examples, as an easier starting point?
- Exact explanations on how `async` and `await` keywords are going to be used
- Timeline? When is this gonna be ready?

**Comment by skade** [comment]
I would not go into details of writing executors in the basic course.

**Comment by spacekookie** [comment]
Note for future self: https://github.com/emilio/bindgen-talk/blob/master/magick-wand-rs/src/main.rs

**Pull request merged**
